DjangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('posts.urls')),  # posts/
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('category/<int:category_id>/', views.category, name='category'),
    path('category/<int:category_id>/<int:pg>/', views.category, name='category'),
    path('post/<int:postId>/', views.detail, name='detail'),  # регуль виражение, захватывает цифры и передает в views.detail
    # path('<int:postId>/', views.detail, name='detail')
    path('page/<int:page>/', views.index, name='page')
]

posts/models.py
from django.db import models
import datetime
# from django.contrib.auth.models import User




class Post(models.Model):

    class Meta():
        ordering = ["postDateCreate"]

    postTitle = models.CharField('postTitle', max_length=200)
    postAuthor = models.CharField('authorName', max_length=50)
    postText = models.TextField('postText')
    postDateCreate = models.DateTimeField('dateOfCreate', auto_now_add=True)
    postDatePublication = models.DateTimeField('dateOfPub', blank=True, null=True)
    postDateLastRefresh = models.DateTimeField('dateOfRefresh', auto_now=True)
    published = models.BooleanField('published', default=False)
    image = models.ImageField('image', blank=True, null=True, upload_to='posts/')
    category = models.ForeignKey('Category', on_delete=models.PROTECT, null=True, blank=True)

    def save(self, *args, **kwargs):

        if self.published and self.postDatePublication is None:
            self.postDatePublication = datetime.datetime.now()
        elif not self.published and self.postDatePublication is not None:
            self.pub_date = None
        super().save(*args, **kwargs)

    def showPartOfText(self, how=300):
        return self.postText[:how]

    def __str__(self):
        return self.postTitle


class Category(models.Model):
    name = models.CharField(max_length=20, db_index=True)

    def __str__(self):
        return self.name

posts/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from .models import Post, Category
# Create your views here.
from django.contrib.auth.models import User, Group

# def index(request):
#     return HttpResponse('test site')
# fr = 0
# lr = 10

def initUsr():
    group = Group.objects.get(name="Members")
    users = User.objects.all()
    for user in users:
        if user.is_staff:
            continue
        else:
            user.is_staff = True
            user.groups.add(group)
            user.save()


gpage = 1

def pagePrep(filtrate):
    initUsr()
    fr = 0
    lr = fr + 10
    global gpage
    n = len(filtrate)
    i = 1
    while i != gpage:
        fr = lr
        lr = lr + 10
        i = i + 1

    ar = [ii + 1 for ii in range(n // 10)]
    lastPostList = filtrate.order_by('-postDatePublication')[fr:lr]
    if not ar:
        ar.append(1)
    elif n % 10 != 0:
        ar.append(ar[-1] + 1)
    return {'lastPostList': lastPostList, 'mpage': gpage, 'mnumpage': ar}


# def sendCtgs(request):
#     ctgs = Category.objects.all()
#     return render(request, 'base.html', {'allCategory': ctgs})


def index(request, page=1): # , fr=1, lr=11,  numpage=[1]
    global gpage
    gpage = page
    initUsr()
    filtrate = Post.objects.filter(published=True)
    resdict = pagePrep(filtrate)
    # resdict['allCategory'] = Category.objects.all()
    return render(request, 'posts/main.html', resdict)


# def page(request, page=1):

    # if not ar:
    #     ar = [1]
    # return index(request, fr, to, page=page, numpage=ar) # render(request, 'posts/page.html', {'page': page})


def detail(request, postId):
    initUsr()
    try:
        a = Post.objects.get(id=postId)
        # b = Category.objects.all()
    except:
        raise Http404('Пост не найден')
    return render(request, 'posts/detail.html', {'post': a})


def category(request, category_id, pg=1):
    initUsr()
    global gpage
    gpage = pg
    postsOfCateg = Post.objects.filter(category=category_id, published=True)
    resdict = dict()
    resdict.update(pagePrep(postsOfCateg))
    # resdict['allCategory'] = Category.objects.all()
    resdict['nowCategory'] = Category.objects.get(pk=category_id)
    return render(request, 'posts/category.html', resdict)




# def detail(request, question_id):
#     return HttpResponse("You're looking at question %s." % question_id)
#
#
# def results(request, question_id):
#     response = "You're looking at the results of question %s."
#     return HttpResponse(response % question_id)
#
#
# def vote(request, question_id):
#   return HttpResponse("You're voting on question %s." % question_id)#

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}My blog{% endblock %}</title>
    {% load static %}

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'style/images/favicon.png' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" media="all"/>
    <link rel="stylesheet" type="text/css" href="{% static 'style/color/red.css' %}" media="all"/>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'style/css/prettyPhoto.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'style/type/museo.css' %}" media="all"/>
    <link rel="stylesheet" type="text/css" href="{% static 'style/type/ptsans.css' %}" media="all"/>
    <link rel="stylesheet" type="text/css" href="{% static 'style/type/charis.css' %}" media="all"/>

    <script type="text/javascript" src="{% static 'style/js/jquery-1.6.2.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'style/js/ddsmoothmenu.js' %}"></script>
    <script type="text/javascript" src="{% static 'style/js/transify.js' %}"></script>
    <script type="text/javascript" src="{% static 'style/js/jquery.prettyPhoto.js' %}"></script>
    <script type="text/javascript" src="{% static 'style/js/jquery.superbgimage.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'style/js/jquery.slickforms.js' %}"></script>
    <!--    <link rel="stylesheet" type="text/css" href="{% static 'posts/style.css' %}">-->
</head>
<body>
<div id="thumbs">
    <a href="{% static 'style/images/art/bg1.jpg' %}">1</a>
    <a href="{% static 'style/images/art/bg2.jpg' %}">2</a>
    <a href="{% static 'style/images/art/bg3.jpg' %}">3</a>
    <a href="{% static 'style/images/art/bg4.jpg' %}">4</a>
    <a href="{% static 'style/images/art/bg5.jpg' %}">5</a>
    <a href="{% static 'style/images/art/bg6.jpg' %}">6</a>
</div>
<div id="superbgimage">
    <div class="scanlines"></div>
</div>
<div id="wrapper">
    <div id="header">
        <div class="logo"><a href="index.html"><img src="{% static 'style/images/logo.png' %}" alt=""/></a></div>
        <div class="social">
            <ul>
                <li><a href="#"><img src="{% static 'style/images/icon-rss.png' %}" alt="RSS"/></a></li>
                <li><a href="#"><img src="{% static 'style/images/icon-facebook.png' %}" alt="Facebook"/></a></li>
                <li><a href="#"><img src="{% static 'style/images/icon-twitter.png' %}" alt="Twitter"/></a></li>
                <li><a href="#"><img src="{% static 'style/images/icon-googleplus.png' %}" alt="Google+"/></a></li>
                <li><a href="#"><img src="{% static 'style/images/icon-dribble.png' %}" alt="Dribble"/></a></li>
                <li><a href="#"><img src="{% static 'style/images/icon-flickr.png' %}" alt="Flickr"/></a></li>
                <li><a href="#"><img src="{% static 'style/images/icon-tumblr.png' %}" alt="Tumblr"/></a></li>
            </ul>
        </div>
    </div>
    <div class="clear"></div>
    <div id="menu" class="menu opacity">
        <ul>
            <li><a href="/" class="active">Home</a></li><!--/index.html-->

            
        </ul>
        <br style="clear: left"/>
    </div>

    <div id="container" class="opacity">

        <!-- Begin Blog -->
        <div class="blog">

            <!-- Begin Posts -->
            <div class="content">



                {% block content %}{% endblock %}


            </div>
        </div>


        <!-- SIDEBAR-->
        <div class="sidebar">

            <div class="sidebar-box">
                <div class="sidebar-box loginLink">
                    {% if user.is_authenticated %}
                    <h4 class="username">Welcome, {{ user.get_username }}</h4>
                    <a href="{% url 'admin:index' %}" ><button class="linkToAdmin">Link to Admin Panel</button></a>
                    <a href="{% url 'logout'%}?next={{request.path}}" ><button class="login">Logout</button></a>
                    {% else %}
                    <a href="{% url 'login'%}?next={{request.path}}" ><button class="login">Login</button></a>
                    {% endif %}
                </div>
                <div class="sidebar-box tags">
                <h4>Tags</h4>
                <div class="tag-list">
                    <ul>
                        {% if allCategory %}{% for i in allCategory %}<li><a href="{% url 'posts:category' i.id %}">{{i.name}}</a></li>{% endfor %}{% endif %}
                    </ul>
                </div>
                </div>
            </div>


        </div>
        <div class="clear"></div>
        <!--          </div>-->
        <!--  </div>-->
        <div id="footer">
            <div class="footer-top"></div>
            <!-- Divider -->


            <div class="one-fourth">
                <h3>About</h3>
                <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.
                    Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Curabitur blandit tempus
                    porttitor.</p> <br/>
                <p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.</p>
            </div>

            <!-- Form -->

            <!-- End Form -->
            <div class="clear"></div>
        </div>
    </div>
    <!-- End Container -->

    <div id="copyright" class="opacity">
        <p>© 2011 Zeences Design. All Right Reserved.</p>
    </div>
</div>
<!-- End Wrapper -->

<script type="text/javascript" src="{% static 'style/js/scripts.js' %}"></script>
</body>
</html>

templates/posts/category.html
{% extends 'base.html' %}

{% block title %}{{ nowCategory }}{% endblock %}

{% block content %}
<h2>Latest Posts</h2>
{% if lastPostList %}
{% for i in lastPostList %}
<div class="post">
    <!-- Begin Post Info -->
    <div class="post-info">
        <!-- Begin Date -->
        <div class="post-date">
            <span class="day">{{i.postDatePublication.day}}</span>
            <span class="month">{{i.postDatePublication|date:"M"}}</span>
            <span class="year">{{i.postDatePublication.year}}</span>
        </div>
        <!-- End Date -->
        <!-- Begin Title -->
        <div class="post-title">
            <h1><a href="{% url 'posts:detail' i.id %}">{{i.postTitle}}</a></h1>
            <!--            <div class="post-meta">-->
            <!--                <span class="comments">-->
            <!--                    <a href="#">13 Comments</a>-->
            <!--                </span>-->
            <!--                <span class="categories">-->
            <!--                <a href="#">Web Design</a>, <a href="#">Photography</a>-->
            <!--                </span>-->
            <!--            </div>-->
        </div>
        <!-- End Title -->
    </div>
    <!-- End Post Info -->

    <div class="post-text">
        {% if i.image %}
        <a href="{% url 'posts:detail' i.id %}">

            <img src="{{i.image.url}}" alt=""/>

        </a> <br/>
        {% endif %}
        <p>{{i.showPartOfText}}<a class="more" href="{% url 'posts:detail' i.id %}">Continue Reading
            →</a>
        </p>
    </div>
    <span class="tags"><a href="{% if i.category %}{% url 'posts:category' i.category.pk %}{% else %}#{% endif %}">{{i.category}}</a></span>
    <!-- End Text -->
<!--    <span class="tags"><a href="#">Black & White</a>, <a href="#">Color</a>, <a href="#">Portfolio</a></span>-->
</div>


{% endfor %}
{% endif %}
<div class="page-navi">
    <p>Page {{ mpage }} of {{ mnumpage|length }}</p>
    <ul>
        {% for i in mnumpage %}
        <li><a href="{% url 'posts:category' nowCategory.pk i %}" {% if mpage == i %}class="current"{% endif %} >{{ i }}</a></li>
        {% endfor %}
<!--        <li><a href="#">2</a></li>-->
<!--        <li><a href="#">3</a></li>-->
    </ul>
</div>


{% endblock %}

templates/posts/detail.html
{% extends 'base.html' %}

{% block title %}{{post.postTitle}}{% endblock %}

{% block content %}

<div class="post">
    <!-- Begin Post Info -->
    <div class="post-info">
        <!-- Begin Date -->
        <div class="post-date">
            <span class="day">{{post.postDatePublication.day}}</span>
            <span class="month">{{post.postDatePublication|date:"M"}}</span>
            <span class="year">{{post.postDatePublication.year}}</span>
        </div>
        <!-- End Date -->
        <!-- Begin Title -->
        <div class="post-title">
            <h1>{{post.postTitle}}</h1>
<!--            <div class="post-meta">-->
<!--                <span class="comments">-->
<!--                    <a href="#">13 Comments</a>-->
<!--                </span>-->
<!--                <span class="categories">-->
<!--                <a href="#">Web Design</a>, <a href="#">Photography</a>-->
<!--                </span>-->
<!--            </div>-->
        </div>
        <!-- End Title -->
    </div>
    <!-- End Post Info -->
<!--<h1>{{post.postTitle}}</h1>-->
<!--<p>{{post.postAuthor}}</p>-->
<!--<p>{{post.postText}}</p>-->
<!--<p>{{post.postDateCreate}}</p>-->
<!--<p>{{post.postDatePublication}}</p>-->
<!--<p>{{post.postDateLastRefresh}}</p>-->
<!--<p>{{post.image}}</p>-->
    <div class="post-text">
        {% if post.image %}
            <img src="{{post.image.url}}" alt=""/>
            <br/>
        {% endif %}
        <p>{{post.postText}}</p>
    </div>
    <!-- End Text -->
    <span class="tags"><a href="{% if post.category %}{% url 'posts:category' post.category.pk %}{% else %}#{% endif %}">{{post.category.name}}</a></span>
    <span class="postsPostInform">Автор: {{post.postAuthor}}</span>
    <span class="postsPostInform">Время создания: {{post.postDateCreate}}</span>
    <span class="postsPostInform">Время публикации: {{post.postDatePublication}}</span>
    <span class="postsPostInform">Время последнего обновления: {{post.postDateLastRefresh}}</span>
</div>

{% endblock %}

templates/posts/main.html
{% extends 'base.html' %}

{% block title %}Blog{% endblock %}

{% block content %}
<h2>Latest Posts</h2>
{% if lastPostList %}
{% for i in lastPostList %}
<div class="post">
    <!-- Begin Post Info -->
    <div class="post-info">
        <!-- Begin Date -->
        <div class="post-date">
            <span class="day">{{i.postDatePublication.day}}</span>
            <span class="month">{{i.postDatePublication|date:"M"}}</span>
            <span class="year">{{i.postDatePublication.year}}</span>
        </div>
        <!-- End Date -->
        <!-- Begin Title -->
        <div class="post-title">
            <h1><a href="{% url 'posts:detail' i.id %}">{{i.postTitle}}</a></h1>
            <!--            <div class="post-meta">-->
            <!--                <span class="comments">-->
            <!--                    <a href="#">13 Comments</a>-->
            <!--                </span>-->
            <!--                <span class="categories">-->
            <!--                <a href="#">Web Design</a>, <a href="#">Photography</a>-->
            <!--                </span>-->
            <!--            </div>-->
        </div>
        <!-- End Title -->
    </div>
    <!-- End Post Info -->

    <div class="post-text">
        {% if i.image %}
        <a href="{% url 'posts:detail' i.id %}">

            <img src="{{i.image.url}}" alt=""/>

        </a> <br/>
        {% endif %}
        <p>{{i.showPartOfText}}<a class="more" href="{% url 'posts:detail' i.id %}">Continue Reading
            →</a>
        </p>
    </div>
    <span class="tags"><a href="{% if i.category %}{% url 'posts:category' i.category.pk %}{% else %}#{% endif %}">{{i.category}}</a></span>
    <!-- End Text -->
<!--    <span class="tags"><a href="#">Black & White</a>, <a href="#">Color</a>, <a href="#">Portfolio</a></span>-->
</div>


{% endfor %}
{% endif %}
<div class="page-navi">
    <p>Page {{ mpage }} of {{ mnumpage|length }}</p>
    <ul>
        {% for i in mnumpage %}
        <li><a href="{% url 'posts:page' i %}" {% if mpage == i %}class="current"{% endif %} >{{ i }}</a></li>
        {% endfor %}
<!--        <li><a href="#">2</a></li>-->
<!--        <li><a href="#">3</a></li>-->
    </ul>
</div>


{% endblock %}